services:
  db:
    container_name: if-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  ollama:
    container_name: ollama
    image: ollama/ollama:rocm # imagem específica para GPUs AMD
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0:3003
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ollama:/root/.ollama
    ports:
      - '3003:3003'

volumes:
  pgdata:
  ollama:
